### ISSUE TITLE
Interfacing of temperature sensor using I2C

### ISSUE THREAD

**Issue by karthik-b-r** [cu-ecen-aeld/final-project-karthik-b-r#1]
DoD: 

- [x] Display the values from the sensors(MLX90614 and HTU21D) by changing temperature and Humidity Levels on Arduino Uno Board.
- [x] Read the temperature values from the sensor after interfacing it with Raspberry Pi

Blockers:

- [x] [Board Bring up using Yocto](https://github.com/cu-ecen-aeld/final-project-SuryawanshiAbhishek/issues/1)
- [x] [Raspberry pi board bring up using buildroot](https://github.com/cu-ecen-aeld/final-project-AnanthD21/issues/1)

**Comment by karthik-b-r** [comment]
**Task 1**: Procured MLX90614 and HTU21D sensors required for measuring temperature and humidity respectively.

**Task 2**: Tested the sensors by interfacing them on Arduino Uno Board. I was able to verify that the sensors were responding to varying parameters. The sensor test code can be referenced on [this](https://github.com/cu-ecen-aeld/final-project-karthik-b-r/commit/8b26d8285b7a8f776555268efbd281223f8d0456) commit ID.

- MLX90614 (Temperature test)
![Temp_sensor_test_arduino](https://user-images.githubusercontent.com/89834177/161451600-ff311aef-9786-40c2-9400-c9fcad0ce308.jpg)
![Temp_sensor](https://user-images.githubusercontent.com/89834177/161451620-e2b369a2-2c18-4736-89c5-74f1b7bfef35.jpg)

- HTU21D(Humidity test)
![Humidity_sensor_test_arduino](https://user-images.githubusercontent.com/89834177/161451691-67a55a6b-4ce5-4784-8c5b-514e9072c5d9.jpg)
![Humidity_sensor](https://user-images.githubusercontent.com/89834177/161451694-4c06807b-b9de-4f4c-8284-401985102b96.jpg)

**Task 3**: Sensors are being detected on Raspberry Pi board when connected. 

- 0x5A is the address of MLX90614 sensor
- 0x40 is the address of HTU21D sensor
![sensors_detected](https://user-images.githubusercontent.com/89834177/161453219-1f515cae-3c2e-49f5-b784-4ee7a59ca8e0.jpg)
![rpi_connection](https://user-images.githubusercontent.com/89834177/161453227-7735d6ad-2da6-4760-80bf-5453c9191782.jpg)

**Task 4**: Temperature values are being read and displayed after successfully interfacing the sensor with RPi using I2C. The code for I2C user-space driver to interact with sensor can be referenced on [this](https://github.com/cu-ecen-aeld/final-project-karthik-b-r/commit/12ffcc855e128e5de4370a247e31115fc2cff60d) commit ID. The code was locally built using [this](https://github.com/cu-ecen-aeld/final-project-SuryawanshiAbhishek/blob/main/meta-i2c/recipes-i2c-config/i2c-config/files/mlx90614.c) repo and tested.

- The sensor has been configured to measure either the Room Temperature or Object Temperature by using the appropriate macro. Thermopile sensor measures room temperature and IR sensor measures object temperature. The below image shows both the readings.
![Temp_sensor_readings](https://user-images.githubusercontent.com/89834177/161459345-5218782f-1d4a-44ac-8d0f-5827b2fa9834.jpg)

**Comment by karthik-b-r** [comment]
The defined tasks for this sprint has been completed. Hence, closing this issue.
