### ISSUE TITLE
LCD and client code integration and testing

### ISSUE THREAD

**Issue by karthik-b-r** [cu-ecen-aeld/final-project-karthik-b-r#3]
DoD:

- [x] Displaying the values obtained from the client on the LCD

Tasks:

- [x] Integrating the server side code(values obtained from sensors) with the LCD
- [ ] Testing to make sure that the sensors data are displayed as required.

**Comment by karthik-b-r** [comment]
**Task 1**: Interfacing the LCD with the Server RPI containing image build from buildroot.
![IMG_20220418_025411__01](https://user-images.githubusercontent.com/89834177/163785170-1660dcca-5d41-4bb5-8eeb-1bf781278bdc.jpg)

**Task 2**:  I was able to successfully Integrate the server side code(values obtained from sensors) with the LCD. In other words, I was able to display the data sent from sensors.


-  The code can be found on this [commit id : f88d33a](https://github.com/cu-ecen-aeld/final-project-karthik-b-r/commit/f88d33a34e45cc8156a3c5f62572765b1a392e49) in my [GitHub Repo](https://github.com/cu-ecen-aeld/final-project-karthik-b-r)
![LCD_interfaced](https://user-images.githubusercontent.com/89834177/163786313-173c7179-f63d-49c8-99e1-904e8752f88c.jpg)

- However, a small part of work is leftover i.e. testing the complete code and formatting the data being displayed on the LCD. currently, its not formatted. I will be rectifying this by next 2-3 days.
 ![to_be_formatted](https://user-images.githubusercontent.com/89834177/163786849-11d28911-15bf-48e2-b651-15db6542e183.jpg)




**Issue faced**: One of our RPI board is not booting(stopped working out of nowhere) and due to this constraint I was unable to format the data displayed on LCD in a readable manner. I would be fixing this soon. I also spent time on trying to figure out the reason why the board is not booting and if there was a way to fix the bootloader. At the end of sprint 3, I was unsuccessful in figuring out/fixing the issue with one of the board. 

**Other tasks performed in this sprit**: Looked around different ways of interfacing public cloud with out project. Researched a bit about GCP's [IoT Core service](https://cloud.google.com/iot/docs). Here is the link to one of the [article](https://medium.com/google-cloud/cloud-iot-step-by-step-connecting-raspberry-pi-python-2f27a2893ab5#ed16) that I found which can be used as an initial step to proceed towards cloud. Since we are blocked with one of our boards being non functional, the priority would be to fix it or arrange alternate source prior to project demo. If we are able to fix our board issue soon, then might plan to log the data to the cloud.
